# A descriptive name for your workflow
name: ML Model CI

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs to be run
jobs:
  build-and-test:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    # Define the sequence of steps in the job
    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.9 environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install the project dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint the code with flake8 for style checks
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Run the unit tests with pytest
      - name: Test with pytest
        run: |
          pytest
